-- 手動適用用SQL
-- 1) 本SQLをSQL Editorで実行
-- 2) get_unread_notification_count / get_notifications / mark_all_notifications_read を確認

begin;

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  actor_user_id uuid not null references public.profiles(id) on delete cascade,
  type text not null,
  workout_run_id bigint null references public.workout_runs(id) on delete cascade,
  created_at timestamptz not null default now(),
  read_at timestamptz null,
  meta jsonb not null default '{}'::jsonb
);

alter table public.notifications
  add column if not exists user_id uuid references public.profiles(id) on delete cascade,
  add column if not exists actor_user_id uuid references public.profiles(id) on delete cascade,
  add column if not exists type text,
  add column if not exists workout_run_id bigint references public.workout_runs(id) on delete cascade,
  add column if not exists created_at timestamptz default now(),
  add column if not exists read_at timestamptz,
  add column if not exists meta jsonb default '{}'::jsonb;

update public.notifications
set meta = '{}'::jsonb
where meta is null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'notifications_type_check'
      and conrelid = 'public.notifications'::regclass
  ) then
    alter table public.notifications
      add constraint notifications_type_check
      check (type in ('like', 'follow', 'follow_request')) not valid;
  end if;
end $$;

create index if not exists idx_notifications_user_read_created
  on public.notifications (user_id, read_at, created_at desc);

create index if not exists idx_notifications_user_created
  on public.notifications (user_id, created_at desc);

alter table public.notifications enable row level security;

drop policy if exists notifications_select_own on public.notifications;
create policy notifications_select_own
on public.notifications
for select
using (auth.uid() = user_id);

drop policy if exists notifications_update_read_own on public.notifications;
create policy notifications_update_read_own
on public.notifications
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create or replace function public.notify_like_insert()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_owner_id uuid;
begin
  select wr.user_id into v_owner_id
  from public.workout_runs wr
  where wr.id = new.run_id;

  if v_owner_id is null or v_owner_id = new.user_id then
    return new;
  end if;

  insert into public.notifications(user_id, actor_user_id, type, workout_run_id, meta)
  values (v_owner_id, new.user_id, 'like', new.run_id, '{}'::jsonb);

  return new;
end;
$$;

create or replace function public.notify_follow_insert()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.followee_id is null or new.follower_id is null or new.followee_id = new.follower_id then
    return new;
  end if;

  insert into public.notifications(user_id, actor_user_id, type, workout_run_id, meta)
  values (new.followee_id, new.follower_id, 'follow', null, '{}'::jsonb);

  return new;
end;
$$;

create or replace function public.notify_follow_request_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status <> 'pending' then
    return new;
  end if;

  if tg_op = 'UPDATE' and coalesce(old.status, '') = 'pending' then
    return new;
  end if;

  insert into public.notifications(user_id, actor_user_id, type, workout_run_id, meta)
  values (new.target_id, new.requester_id, 'follow_request', null, '{}'::jsonb);

  return new;
end;
$$;

drop trigger if exists trg_notify_like_insert on public.workout_run_likes;
create trigger trg_notify_like_insert
after insert on public.workout_run_likes
for each row execute function public.notify_like_insert();

drop trigger if exists trg_notify_follow_insert on public.follows;
create trigger trg_notify_follow_insert
after insert on public.follows
for each row execute function public.notify_follow_insert();

drop trigger if exists trg_notify_follow_request_insert on public.follow_requests;
create trigger trg_notify_follow_request_insert
after insert on public.follow_requests
for each row execute function public.notify_follow_request_change();

drop trigger if exists trg_notify_follow_request_update on public.follow_requests;
create trigger trg_notify_follow_request_update
after update of status on public.follow_requests
for each row execute function public.notify_follow_request_change();

create or replace function public.get_unread_notification_count()
returns table (unread_count bigint)
language sql
security invoker
set search_path = public
as $$
  select count(*)::bigint as unread_count
  from public.notifications n
  where n.user_id = auth.uid()
    and n.read_at is null;
$$;

create or replace function public.mark_all_notifications_read()
returns table (updated_count bigint)
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_count bigint;
begin
  update public.notifications
  set read_at = now()
  where user_id = auth.uid()
    and read_at is null;

  get diagnostics v_count = row_count;
  return query select coalesce(v_count, 0)::bigint;
end;
$$;

create or replace function public.get_notifications(
  p_limit int default 30,
  p_before timestamptz default null
)
returns table (
  notification_id bigint,
  notification_type text,
  created_at timestamptz,
  read_at timestamptz,
  actor_id uuid,
  actor_display_name text,
  run_id bigint,
  workout_created_at timestamptz,
  workout_exercise_slug text,
  has_pending_request boolean,
  is_following_actor boolean,
  message text
)
language sql
security invoker
set search_path = public
as $$
  select
    n.id as notification_id,
    n.type as notification_type,
    n.created_at,
    n.read_at,
    n.actor_user_id as actor_id,
    coalesce(p.display_name, n.actor_user_id::text) as actor_display_name,
    n.workout_run_id as run_id,
    coalesce(wr.published_at, wr.created_at) as workout_created_at,
    coalesce(wr.result->>'exerciseSlug', wr.result->>'exercise_slug', wr.result->>'questId', wr.result->>'quest_id') as workout_exercise_slug,
    exists (
      select 1
      from public.follow_requests fr
      where fr.requester_id = n.actor_user_id
        and fr.target_id = auth.uid()
        and fr.status = 'pending'
    ) as has_pending_request,
    exists (
      select 1
      from public.follows f
      where f.follower_id = auth.uid()
        and f.followee_id = n.actor_user_id
    ) as is_following_actor,
    case n.type
      when 'like' then coalesce(p.display_name, n.actor_user_id::text) || ' さんがあなたの投稿にいいねしました。'
      when 'follow' then coalesce(p.display_name, n.actor_user_id::text) || ' さんがあなたをフォローしました。'
      when 'follow_request' then coalesce(p.display_name, n.actor_user_id::text) || ' さんからフォローリクエストがあります。'
      else '通知'
    end as message
  from public.notifications n
  left join public.profiles p on p.id = n.actor_user_id
  left join public.workout_runs wr on wr.id = n.workout_run_id
  where n.user_id = auth.uid()
    and (p_before is null or n.created_at < p_before)
  order by n.created_at desc
  limit greatest(coalesce(p_limit, 30), 1);
$$;

grant execute on function public.get_unread_notification_count() to authenticated;
grant execute on function public.mark_all_notifications_read() to authenticated;
grant execute on function public.get_notifications(int, timestamptz) to authenticated;

commit;

-- 動作確認SQL:
-- select * from public.get_unread_notification_count();
-- select * from public.get_notifications(50, null);
-- select * from public.mark_all_notifications_read();
