const fs = require('fs/promises');
const path = require('path');

const projectRoot = path.resolve(__dirname, '..');
const srcDir = path.join(projectRoot, 'src');
const distDir = path.join(projectRoot, 'dist');

async function clean() {
  await fs.rm(distDir, { recursive: true, force: true });
}

async function copyDir(from, to) {
  await fs.mkdir(to, { recursive: true });
  const entries = await fs.readdir(from, { withFileTypes: true });

  for (const entry of entries) {
    const sourcePath = path.join(from, entry.name);
    const targetPath = path.join(to, entry.name);

    if (entry.isDirectory()) {
      await copyDir(sourcePath, targetPath);
    } else if (entry.isFile()) {
      await fs.copyFile(sourcePath, targetPath);
    }
  }
}

async function loadQuests() {
  const questsPath = path.join(srcDir, 'data', 'quests.json');
  const json = await fs.readFile(questsPath, 'utf-8');
  return JSON.parse(json);
}

function extractExerciseMeta(html, fallbackSlug) {
  const titleMatch = html.match(/<title>([^<]*)<\/title>/i);
  const bodyMatch = html.match(/<body[^>]*>([\s\S]*?)<\/body>/i);

  return {
    title: titleMatch ? titleMatch[1].trim() : fallbackSlug,
    body: bodyMatch ? bodyMatch[1].trim() : html.trim(),
  };
}

async function loadExercises() {
  const exercisesDir = path.join(srcDir, 'content', 'exercises');
  const entries = await fs.readdir(exercisesDir, { withFileTypes: true });

  const exercises = {};
  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith('.html')) continue;

    const slug = path.basename(entry.name, '.html');
    const fullPath = path.join(exercisesDir, entry.name);
    const html = await fs.readFile(fullPath, 'utf-8');
    const { title, body } = extractExerciseMeta(html, slug);

    exercises[slug] = { title, body };
  }

  return exercises;
}

function createContentModule(quests, exercises) {
  const questsJson = JSON.stringify(quests, null, 2);
  const exercisesJson = JSON.stringify(exercises, null, 2);

  return `// Auto-generated by scripts/build.js. Do not edit directly.\n\nexport const quests = ${questsJson};\n\nexport const exercises = ${exercisesJson};\n\nexport const questIndex = new Map(quests.map((quest) => [quest.id, quest]));\n\nexport function findQuestById(id) {\n  return questIndex.get(id);\n}\n\nexport function listQuestsByTier(tier) {\n  return quests.filter((quest) => quest.tier === tier);\n}\n\nexport function getExercise(slug) {\n  return exercises[slug];\n}\n`;
}

async function generateContentModule() {
  const [quests, exercises] = await Promise.all([loadQuests(), loadExercises()]);
  const moduleSource = createContentModule(quests, exercises);

  const generatedDir = path.join(distDir, 'generated');
  await fs.mkdir(generatedDir, { recursive: true });
  await fs.writeFile(path.join(generatedDir, 'contentMap.js'), moduleSource, 'utf-8');
}

async function build() {
  await clean();
  await copyDir(srcDir, distDir);
  await generateContentModule();
  console.log('Build complete: dist/ mirrors src/ with generated content map.');
}

if (require.main === module) {
  build().catch((error) => {
    console.error(error);
    process.exitCode = 1;
  });
}

module.exports = { build, distDir };
